
site_name: Mocha
site_description: ""
site_url: "https://mardix.github.com/mocha"
copyright: 'Copyright &copy; 2016 - 2017++ Mardix'

repo_url: https://github.com/mardix/mocha
repo_name: "Mocha"
theme: "material" # readthedocs

markdown_extensions:
  - admonition
  - codehilite
  - markdown_include.include:
      base_path: docs

extra:
  palette:
    primary: 'Brown'
    accent: 'Amber'

pages:

  - Home: index.md
  - Setup: setup.md
  - First App: first-app.md
  - Config: config.md

  - Views: views/index.md
  - "Views: Decorators": views/decorators.md
  - "Views: Helpers": views/helpers.md

  - Templates: templates/index.md
  - "Templates: Filters": templates/filters.md

  - Templates Components:
    - Forms: templates/forms.md
    - Widgets: templates/widgets.md
    - Navs: templates/navs.md

  - Models: models.md
  - Assets: assets.md
  - Extensions: ext.md
  - Arrow: arrow.md
  - Utils: utils.md
  - Pagination: pagination.md
  - Signals: signals.md
  - Logging: logging.md

  - Contrib: contrib/index.md
  - Auth: contrib/auth.md
  - Admin: contrib/admin.md
  - Contact Page: contrib/contact-page.md
  - Error Page: contrib/error-page.md
  - Error Page: contrib/maintenance-page.md
  - Exceptions: exceptions.md
  - CLI: cli.md
  - Deployment: deploy.md
#  - Snippets:
#    - Home: snippets/index.md


